commands:
  # Hora
  - commmand:
    input:  Que horas são?
    entity: time
    action: getTime
  - commmand:
    input:  Me digas horas.
    entity: time
    action: getTime
  - commmand:
    input:  Eu quero saber as horas.
    entity: time
    action: getTime
  # Data
  - commmand:
    input:  Qual é a data de hoje?
    entity: time
    action: getDate
  - commmand:
    input:  Data de hoje.
    entity: time
    action: getDate
  # Tempo
  - commmand:
    input:  Previsão do tempo
    entity: weather
    action: getWeather
  - commmand:
    input:  Como está o clima?
    entity: weather
    action: getWeather
  # Open
  - commmand:
    input:  Abrir bloco de notas
    entity: open
    action: notepad
  - commmand:
    input:  Abrar o bloco de notas
    entity: open
    action: notepad
  - commmand:
    input:  Abrir chrome
    entity: open
    action: chrome
  - commmand:
    input:  Abra chrome
    entity: open
    action: chrome
  # Cria projeto
  - commmand:
    input:  cria projeto
    entity: agvs
    action: criaprojeto
  - commmand:
    input:  criar projeto
    entity: agvs
    action: criaprojeto
  - commmand:
    input:  iniciar projeto
    entity: agvs
    action: criaprojeto
  - commmand:
    input:  começar projeto
    entity: agvs
    action: criaprojeto
  - commmand:
    input:  cria projetos
    entity: agvs
    action: criaprojeto
  - commmand:
    input:  criar projetos
    entity: agvs
    action: criaprojeto
  - commmand:
    input:  iniciar projetos
    entity: agvs
    action: criaprojeto
  - commmand:
    input:  começar projetos
    entity: agvs
    action: criaprojeto